{{- if .Values.lightspeedCore.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mcp-kubernetes-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aladdin.k8sMcp.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "aladdin.k8sMcp.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.k8sMcp.service.port }}
      targetPort: {{ .Values.k8sMcp.service.targetPort }}
  type: ClusterIP
{{- end }}
