{{- if .Values.lightspeedCore.llm.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.lightspeedCore.llm.apiKeySecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aladdin.lightspeedCore.labels" . | nindent 4 }}
type: Opaque
stringData:
  apitoken: {{ .Values.lightspeedCore.llm.apiKey | quote }}
{{- end }}
