{{- if .Values.obsMcp.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: genie-obs-mcp-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aladdin.obsMcp.labels" . | nindent 4 }}
{{- end }}
