{{- if .Values.olsConfig.llm.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.olsConfig.llm.apiKeySecretName }}
  namespace: {{ .Values.olsSubscription.namespace }}
  labels:
    {{- include "aladdin.lightspeedCore.labels" . | nindent 4 }}
type: Opaque
stringData:
  apitoken: {{ .Values.olsConfig.llm.apiKey | quote }}
{{- end }}
