{{- if .Values.olsConfig.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    # Helm hooks ensure namespace is created before other OLS resources
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    security.openshift.io/MinimallySufficientPodSecurityStandard: restricted
  labels:
    kubernetes.io/metadata.name: {{ .Values.olsSubscription.namespace }}
    openshift.io/cluster-monitoring: "true"
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
    security.openshift.io/scc.podSecurityLabelSync: "true"
  name: {{ .Values.olsSubscription.namespace }}
spec:
  finalizers:
  - kubernetes
{{- end }}
