{{- if .Values.plugin.jobs.patchConsoles.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "aladdin.plugin.patcherName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aladdin.plugin.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "aladdin.plugin.patcherName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "aladdin.plugin.patcherServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
