{{- if .Values.plugin.jobs.patchConsoles.enabled }}
# Combined patcher job that:
# 1. Adds the console plugin to the list of enabled plugins in consoles.operator.openshift.io/cluster
# 2. No longer needs to patch the ConsolePlugin proxy since it's created with correct settings
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "aladdin.plugin.patcherName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aladdin.plugin.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  parallelism: 1
  template:
    metadata:
      labels:
        {{- include "aladdin.plugin.labels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ template "aladdin.plugin.patcherServiceAccountName" . }}
      {{- if and (.Values.plugin.securityContext.enabled) (.Values.plugin.jobs.patchConsoles.podSecurityContext.enabled) }}
      securityContext: {{ tpl (toYaml (omit .Values.plugin.jobs.patchConsoles.podSecurityContext "enabled")) $ | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 400
      dnsPolicy: ClusterFirst
      containers:
        - name: {{ template "aladdin.plugin.patcherName" . }}
          image: {{ required "Patcher image must be specified!" .Values.plugin.jobs.patchConsoles.image }}
          {{- if and (.Values.plugin.securityContext.enabled) (.Values.plugin.containerSecurityContext) }}
          securityContext: {{ tpl (toYaml (omit .Values.plugin.jobs.patchConsoles.containerSecurityContext "enabled")) $ | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.plugin.jobs.patchConsoles.resources | nindent 12 }}
          command:
            - /bin/bash
            - -c
            - |
              set -e
              echo "=== Aladdin Console Plugin Patcher ==="
              
              # Step 1: Add plugin to the console's enabled plugins list
              echo "Adding {{ template "aladdin.plugin.name" . }} to enabled console plugins..."
              existingPlugins=$(oc get consoles.operator.openshift.io cluster -o json | jq -c '.spec.plugins // []')
              mergedPlugins=$(jq --argjson existingPlugins "${existingPlugins}" --argjson consolePlugin '["{{ template "aladdin.plugin.name" . }}"]' -c -n '$existingPlugins + $consolePlugin | unique')
              patchedPlugins=$(jq --argjson mergedPlugins $mergedPlugins -n -c '{ "spec": { "plugins": $mergedPlugins } }')
              oc patch consoles.operator.openshift.io cluster --patch $patchedPlugins --type=merge
              
              echo "=== Patcher completed successfully ==="
{{- end }}
