{{- if .Values.plugin.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aladdin.plugin.serviceAccountName" . }}
  labels:
    {{- include "aladdin.plugin.labels" . | nindent 4 }}
  {{- with .Values.plugin.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
