# Next Gen UI Configuration for Openshift MCP
---
input_data_json_wrapping: true
unsupported_components: true

data_types:
  namespaces_list:
    data_transformer: fwctable
    components:
      - component: table
        configuration:
          title: Namespaces
          fields:
            - name: Name
              data_path: $[*].NAME
            - name: Status
              data_path: $[*].STATUS
            - name: Age
              data_path: $[*].AGE
  projects_list:
    data_transformer: fwctable
  events_list:
    data_transformer: fwctable
  pods_get:
    data_transformer: yaml
  pods_list:
    data_transformer: fwctable
  pods_list_in_namespace:
    data_transformer: fwctable
    components:
      - component: table
        configuration:
          title: Pods
          fields:
            - name: Name
              data_path: $[*].NAME
            - name: Status
              data_path: $[*].STATUS
            - name: Ready
              data_path: $[*].READY
            - name: Age
              data_path: $[*].AGE
            - name: IP
              data_path: $[*].IP
            - name: Node
              data_path: $[*].NODE
  pods_log:
    data_transformer: noop
    components:
      - component: log
  resources_list:
    data_transformer: fwctable
